# Generated by Django 5.1.1 on 2024-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.hobby'),
        ),
    ]
