# Generated by Django 5.1.1 on 2024-12-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies',
        ),
    ]
