# Generated by Django 5.1.1 on 2024-12-18 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='users',
            field=models.ManyToManyField(related_name='hobbies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
